version: '3'

services:
  frontend:
    build:
      context: marvel_services
    container_name: frontend
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./Marvel_services:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - '5173:3000'
    command: npm run start

  backend:
    build:
      context: res
    container_name: backend
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./res:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - '5175:3001'
    command: npm run start

  # nginx:
  #   build:
  #     context: nginx
  #   container_name: nginx
  #   restart: always
  #   tty: true
  #   ports:
  #     - '8000:80'
  #   networks:
  #     - node-network
  #   depends_on:
  #     - frontend

networks:
  node-network:
    driver: bridge


